import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/_components/layout/Header'

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={"min-h-screen overflow-x-hidden"}>
        <Header />
        <main>{children}</main>
        <ToastContainer />
      </body>
    </html>
  )
}
